name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    env:
      folders: "'', '\\UI', '\\UI\\Minimap\\Golden'"
    steps:
      - uses: actions/checkout@v2
      - name: test1
        run: echo Hello
      - name: dir
        run: dir
      - name: count-files
        run: (Get-ChildItem source-pngs -Recurse -File | Measure-Object).Count
      - name: downscale-pngs
        run: |
          foreach( $folder in $folders ) {
            echo "folder: $folder"
            (New-Item $output$folder -ItemType directory)
            tools\downscale_pngs.exe $input$folder $output$folder
          }
        env:
          input: 'source-pngs'
          output: 'temp2'
      - name: count-files
        run: (Get-ChildItem temp2 -Recurse -File | Measure-Object).Count
