name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test1
        run: echo Hello
      - name: dir
        run: dir
      - name: count-files
        run: (Get-ChildItem source-pngs -Recurse -File | Measure-Object).Count
