name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    env:
      folders: "'', '\\UI', '\\UI\\Minimap\\Golden'"
    steps:
      - uses: actions/checkout@v2
      - name: test1
        run: echo Hello
      - name: dir
        run: dir
      - name: count-files
        run: (Get-ChildItem source-pngs -Recurse -File | Measure-Object).Count
      - name: downscale-pngs
        # run: |
        #   $folders = '',
        #     '\UI',
        #     '\UI\WorldGen',
        #     '\UI\PlayerResourceSets',
        #     '\UI\PlayerResourceSets\HorizontalBars',
        #     '\UI\PlayerResourceSets\FancyClassic',
        #     '\UI\CharCreation',
        #     '\UI\WorldCreation',
        #     '\UI\Minimap',
        #     '\UI\Minimap\Leaf',
        #     '\UI\Minimap\StoneGold',
        #     '\UI\Minimap\Golden',
        #     '\UI\Minimap\Default',
        #     '\UI\Minimap\Valkyrie',
        #     '\UI\Minimap\TwigLeaf',
        #     '\UI\Minimap\Sticks',
        #     '\UI\Minimap\Retro',
        #     '\UI\Minimap\Remix',
        #     '\UI\Bestiary',
        #     '\UI\Bestiary\NPCs',
        #     '\UI\Creative',
        #     '\Accessories',
        #     '\TownNPCs',
        #     '\Armor'

        #   $input = 'source-pngs'
        #   $output = 'temp2'
        #   foreach( $folder in $folders ) {
        #     echo "folder: $folder"
        #     (New-Item $output$folder -ItemType directory)
        #     tools\downscale_pngs.exe $input$folder $output$folder
        #   }
        run: |
          echo "folders: ${Env:folders}"
          echo "input: ${Env:input}"
          echo "output: ${Env:output}"
          $folders = [Environment]::GetEnvironmentVariable('folders', 'Machine')
          $input = [Environment]::GetEnvironmentVariable('input', 'Machine')
          $output = [Environment]::GetEnvironmentVariable('output', 'Machine')
          echo "folders2: ${Env:folders}"
          echo "input2: ${Env:input}"
          echo "output2: ${Env:output}"

          foreach( $folder in $folders ) {
            echo "folder: $folder"
            (New-Item $output$folder -ItemType directory)
            tools\downscale_pngs.exe $input$folder $output$folder
          }
        env:
          input: 'source-pngs'
          output: 'temp2'
      - name: count-files
        run: (Get-ChildItem temp2 -Recurse -File | Measure-Object).Count
